--DROP TABLE CONTRACT CASCADE CONSTRAINTS;

--DROP TABLE TASK CASCADE CONSTRAINTS;

 

CREATE TABLE TASK (

TaskID CHAR(3),

TaskName VARCHAR(20),

ContractCount NUMERIC(1,0) DEFAULT 0,

CONSTRAINT PK_TASK PRIMARY KEY (TaskID)

);

 

CREATE TABLE CONTRACT

(

TaskID CHAR(3),

WorkerID CHAR(7),

Payment NUMERIC(6,2),

CONSTRAINT PK_CONTRACT PRIMARY KEY (TaskID, WorkerID),

CONSTRAINT FK_CONTRACTTASK FOREIGN KEY (TaskID) REFERENCES TASK (TaskID)

);

 

INSERT INTO TASK (TaskID, TaskName) VALUES ('333', 'Security' );

INSERT INTO TASK (TaskID, TaskName) VALUES ('322', 'Infrastructure');

INSERT INTO TASK (TaskID, TaskName) VALUES ('896', 'Compliance' );

 

SELECT * FROM TASK;

COMMIT;